import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  ArrowRightLeft,
  ArrowUpDown,
  BarChart3,
  Bell,
  Building2,
  CalendarCheck,
  CheckCircle,
  Circle,
  ClipboardList,
  Clock,
  Cpu,
  FileText,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  Heart,
  Languages,
  Layers,
  ListChecks,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Package,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  Rocket,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Sliders,
  Target,
  TrendingUp,
  User,
  UserCheck,
  UserPlus,
  Wallet,
  Wrench,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  ArrowRightLeft,
  ArrowUpDown,
  BarChart3,
  Bell,
  Building2,
  CalendarCheck,
  CheckCircle,
  Circle,
  ClipboardList,
  Clock,
  Cpu,
  FileText,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  Heart,
  Languages,
  Layers,
  ListChecks,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Package,
  Phone,
  PhoneCall,
  PhoneIncoming,
  PhoneOutgoing,
  Rocket,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Sliders,
  Target,
  TrendingUp,
  User,
  UserCheck,
  UserPlus,
  Wallet,
  Wrench,
};

type ProgramIconProps = {
  name: string;
  className?: string;
  size?: number;
};

export function ProgramIcon({ name, className, size = 24 }: ProgramIconProps) {
  const Icon = iconMap[name] ?? Circle;
  return <Icon size={size} className={className} style={{ color: "#2CADB2" }} aria-hidden />;
}
